### ISSUE TITLE
npm package has  the wrong version / readme etc

### ISSUE THREAD

**Issue by Fishrock123** [nodejs/nodereport#10]
https://www.npmjs.com/package/nodereport does not line up with here, what's up with that?

**Comment by sam-github** [comment]
@Fishrock123 I just walked @rnchamberlain through npm publish best practice, and we republished with git tags, changelog, all the good stuff.

**Comment by Fishrock123** [comment]
@sam-github it's still not correct? May I suggest unpublishing and re-doing it entirely?

**Comment by sam-github** [comment]
@Fishrock123 previous versions weren't released from a git tag, which can't be fixed. Going forward, releases will look like https://github.com/nodejs/nodereport/releases

**Comment by rnchamberlain** [comment]
@Fishrock123 
Publishing to npm under proper control now, see
https://github.com/nodejs/nodereport/blob/master/CHANGES.md etc, 
OK to close this? thanks

**Comment by Fishrock123** [comment]
I think so.
